// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gtmvksxklgutxsgwlsog.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd0bXZrc3hrbGd1dHhzZ3dsc29nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3MzcxNzgsImV4cCI6MjA3MDMxMzE3OH0.0oVZ-kaL1tbsyJAb7EPZfvu0Kp0TWK7u7Lu0cZgPmZE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});